"""
SubForge — user-facing string constants.

STRINGS is a proxy object. All modules import it once:
    from gui.strings import STRINGS
Calling set_language() at any time updates what STRINGS["key"] returns
for all modules without re-importing anything.
"""
from __future__ import annotations

# ---------------------------------------------------------------------------
# English
# ---------------------------------------------------------------------------

_EN: dict = {
    "app_title":                "SubForge",
    "app_toolbar_label":        "SubForge",
    "app_btn_settings":         "⚙ Settings",
    "app_btn_check_updates":    "Check for Updates",
    "app_btn_checking":         "Checking...",
    "app_version":              "v0.8.0",
    "tab_single_file":          "Single File",
    "tab_batch":                "Batch",
    "tab_video_scan":           "Video Scan",
    "tab_regex_editor":         "Regex Editor",
    "sf_no_file_loaded":        "No file loaded",
    "sf_loading":               "Loading {name}…",
    "sf_lbl_file_queue":        "FILE QUEUE",
    "sf_lbl_subtitle_blocks":   "SUBTITLE BLOCKS",
    "sf_lbl_block_detail":      "BLOCK DETAIL",
    "sf_lbl_file_report":       "FILE REPORT",
    "sf_chk_dry_run":           "Dry run",
    "sf_chk_remove_warnings":   "Remove warnings",
    "sf_btn_open_folder":       "Open Folder…",
    "sf_btn_mark_ad":           "Mark as Ad",
    "sf_btn_keep":              "Keep Block",
    "sf_btn_always_ad":         "Always Mark as Ad...",
    "sf_btn_always_ad_tip":     "Add a regex pattern for this block's text to a profile,\nso it is automatically flagged in all future files.",
    "sf_btn_prev":              "Prev File",
    "sf_btn_next":              "Next File",
    "sf_btn_clean_save":        "Clean && Save",
    "sf_patterns_placeholder":  "Matched patterns will appear here…",
    "sf_drop_label":            "Drop subtitle files here",
    "sf_drop_formats":          ".srt  .ass  .ssa  .vtt",
    "sf_browse":                "Browse…",
    "sens_label":               "Sensitivity:",
    "sens_more_aggressive":     "More aggressive",
    "sens_more_conservative":   "More conservative",
    "thresh_1":                 "Very Aggressive",
    "thresh_2":                 "Aggressive",
    "thresh_3":                 "Balanced (default)",
    "thresh_4":                 "Conservative",
    "thresh_5":                 "Very Conservative",
    "msg_ready":                "Ready — drop subtitle files to begin",
    "msg_analysis_complete":    "Analysis complete — {ads} ad block(s) found, {warns} warning(s)",
    "msg_analysis_complete_opts": "Analysis complete — {ads} ad block(s) found, {warns} warning(s), {opts} opt(s)",
    "msg_error_loading":        "Error loading file",
    "msg_error":                "Error: {msg}",
    "msg_no_blocks":            "No blocks flagged for removal.",
    "msg_saved":                "Saved: {name}",
    "msg_dry_run":              "Dry run complete — no files written.",
    "msg_engine_reloaded":      "Engine reloaded — file re-analysed with new patterns.",
    "dlg_confirm_title":        "Confirm Clean & Save",
    "dlg_confirm_text":         "Remove {n} block(s) from {name}?",
    "dlg_write_error":          "Write Error",
    "msg_checking_updates":     "Checking for updates...",
    "msg_up_to_date":           "SubForge is up to date.",
    "msg_update_failed":        "Update check failed.",
    "dlg_update_available":     "Update Available",
    "dlg_update_text":          "A new version of SubForge is available.\n\nCurrent version:  {current}\nLatest version:   {latest}  ({name})\n\nVisit the releases page to download the update.",
    "dlg_up_to_date_title":     "Up to Date",
    "dlg_up_to_date_text":      "You are running the latest version of SubForge ({version}).",
    "dlg_update_failed_title":  "Update Check Failed",
    "dlg_update_failed_text":   "Could not check for updates.\n\n{error}\n\nCheck your internet connection or visit:\n{url}",
    "batch_btn_select_folder":  "Select Base Folder…",
    "batch_no_folder":          "No folder selected",
    "batch_btn_clear":          "Clear",
    "batch_btn_scan_all":       "Scan All",
    "batch_btn_clean_save_all": "Clean && Save All",
    "batch_btn_open_review":    "Open in Single File Tab",
    "batch_btn_full_report":    "Show Full Report",
    "batch_chk_warnings":       "Also remove warnings (one level below threshold)",
    "batch_lbl_scanned":        "SCANNED FILES",
    "batch_lbl_report":         "BATCH REPORT",
    "batch_status_begin":       "Select a movies folder to begin.",
    "batch_status_scanning":    "Scanning {current}/{total}: {name}",
    "batch_status_complete":    "Scan complete — {total} files · {with_ads} with ads ({blocks} blocks) · {warns} warnings · threshold: rm>={thresh}",
    "batch_no_files":           "No subtitle files found in that folder.",
    "batch_files_queued":       "{n} subtitle file(s) queued.",
    "batch_saving":             "Saving {i}/{total}: {name}",
    "batch_done_status":        "Done — {saved} file(s) cleaned at threshold rm>={thresh}.",
    "batch_tip_full_report":    "Restore the full batch summary report.",
    "dlg_nothing_to_clean":     "Nothing to clean",
    "dlg_nothing_to_clean_msg": "No files have issues at the current threshold.",
    "dlg_confirm_batch":        "Confirm batch clean",
    "dlg_confirm_batch_msg":    "Remove {blocks} block(s) from {files} file(s) and save?\n\nThreshold: regex_matches >= {thresh}\nThis cannot be undone.",
    "dlg_saves_failed":         "Some saves failed",
    "dlg_done":                 "Done",
    "dlg_done_msg":             "{saved} file(s) cleaned and saved.",
    "video_btn_add_folder":     "Add Folder…",
    "video_btn_clear":          "Clear",
    "video_btn_scan":           "Scan Videos",
    "video_btn_extract":        "Extract && Save .srt/.ass",
    "video_btn_remux":          "Clean && Remux",
    "video_lbl_files":          "VIDEO FILES & TRACKS",
    "video_lbl_detail":         "SCAN DETAIL",
    "video_no_folder":          "No folder selected",
    "video_chk_backup":         "Keep backup",
    "video_chk_warnings":       "Also remove warnings",
    "video_drop_label":         "Drop video files here  ·  .mkv  .mp4  .m4v",
    "video_status_complete":    "Scan complete — {total} video(s) · {ads} ad block(s) found in embedded subtitles",
    "video_lbl_selected":       "Check boxes on flagged tracks to select for cleaning",
    "video_files_queued":       "{n} video file(s) queued.",
    "video_status_begin":       "Drop video files or add a folder to begin.",
    "video_status_scanning":    "Scanning {current}/{total}: {name}",
    "video_ffmpeg_notice":      "⚠  ffprobe and ffmpeg not found on PATH. Install FFmpeg (https://ffmpeg.org/download.html).",
    "video_mkv_notice":         "⚠  mkvmerge not found — Clean & Remux is unavailable for MKV files. MP4 and M4V files can still be remuxed using FFmpeg. Install MKVToolNix or set the path via ⚙ Settings to enable MKV remux.",
    "video_remux_tip":          "Rebuild the video file with cleaned subtitle tracks replacing the originals.",
    "video_extract_tip":        "Extract and clean subtitle tracks as standalone files next to the video.",
    "video_lbl_selected_n":     "{n} track(s) selected.",
    "video_starting":           "Starting…",
    "dlg_ffprobe_title":        "ffprobe not found",
    "dlg_ffprobe_msg":          "Install FFmpeg and ensure it is on your PATH.",
    "dlg_extractions_failed":   "Some extractions failed",
    "dlg_mkvmerge_missing":     "mkvmerge not found",
    "dlg_mkvmerge_missing_msg": "Set the mkvmerge path via Settings in the toolbar.",
    "regex_lbl_profiles":       "PROFILES",
    "regex_lbl_editor":         "PATTERN EDITOR",
    "regex_btn_new_profile":    "+ New Profile…",
    "regex_btn_reload":         "Reload Engine",
    "regex_btn_add":            "Add",
    "regex_btn_save":           "Save Profile",
    "regex_btn_discard":        "Discard Changes",
    "regex_placeholder":        "Select a profile on the left to edit it…",
    "regex_desc":               "Edit regex profiles directly. Changes are saved to disk and applied immediately.",
    "regex_unsaved_title":      "Unsaved changes",
    "regex_unsaved_msg":        "You have unsaved changes. Discard them?",
    "regex_valid":              "✓ Valid regex",
    "regex_invalid":            "✕ Invalid: {error}",
    "regex_dirty":              "● Unsaved changes",
    "regex_saved":              "✓ Saved and engine reloaded.",
    "regex_key_placeholder":    "key (e.g. my_purge1)",
    "regex_val_placeholder":    r"regex value (e.g. \bMyWatermark\b)",
    "dlg_invalid_regex":        "Invalid regex",
    "dlg_read_error":           "Read error",
    "dlg_write_error_regex":    "Write error",
    "dlg_invalid_config":       "Invalid config",
    "settings_title":               "SubForge Settings",
    "settings_tab_general":         "General",
    "settings_tab_cleaning":        "Cleaning Options",
    "settings_tab_paths":           "Paths",
    "settings_tab_about":           "About",
    "settings_btn_save":            "Save",
    "settings_btn_cancel":          "Cancel",
    "settings_grp_sensitivity":     "Default Sensitivity",
    "settings_sens_desc":           "Sets the starting sensitivity level when SubForge launches. Applies to Single File, Batch, and Video Scan.",
    "settings_future_grp":          "Coming in v1.0.0",
    "settings_future_theme":        "Theme (dark / light / high contrast)",
    "settings_future_font":         "Font size (small / medium / large)",
    "settings_future_lang":         "Additional languages",
    "settings_cleaning_desc":       "These options modify subtitle content at clean time. They apply globally — the same settings are used in Single File, Batch, and Video Scan. All options are off by default.",
    "settings_sdh_warn":            "Warning: Removing SDH content reduces accessibility for deaf and hard of hearing viewers.",
    "settings_grp_mkv":             "MKVToolNix",
    "settings_mkv_info":            "mkvmerge is used to rebuild MKV files with cleaned subtitle tracks. If it is not on your system PATH, specify the full path to mkvmerge.exe below. Not required for MP4 and M4V files.",
    "settings_mkv_placeholder":     r"e.g. C:\Program Files\MKVToolNix\mkvmerge.exe",
    "settings_mkv_found":           "✓ File found.",
    "settings_mkv_not_found":       "✕ File not found at that path.",
    "settings_mkv_on_path":         "✓ mkvmerge found on PATH: {path}",
    "settings_mkv_missing":         "mkvmerge not found. Install from https://mkvtoolnix.download/",
    "settings_browse":              "Browse…",
    "settings_about_tagline":       "Remove ads, watermarks, and distributor junk from subtitle files.",
    "settings_about_author":        "Created by David R. Babcock",
    "settings_about_license":       "Released under the MIT License.",
    "settings_about_credit":        "Detection engine originally based on subcleaner by KBlixt (MIT).",
    "settings_btn_report_issue":    "Report an Issue",
    "settings_chk_music":           "Remove music cues",
    "settings_chk_music_tip":       "Removes lines consisting entirely of ♪ ♫ music symbols.",
    "settings_chk_sdh":             "Remove SDH annotations",
    "settings_chk_sdh_tip":         "Removes sound descriptions like [DOOR SLAMS] and (LAUGHING).",
    "settings_chk_speakers":        "Remove speaker labels",
    "settings_chk_speakers_tip":    "Removes speaker prefixes like JOHN: or - MARY: at the start of lines.",
    "settings_chk_tags":            "Remove text formatting tags",
    "settings_chk_tags_tip":        "Removes <font> and other HTML tags. Italic and bold can be preserved below.",
    "settings_chk_italic":          "Preserve italic  <i>",
    "settings_chk_bold":            "Preserve bold  <b>",
    "settings_section_removal":     "Content Removal",
    "settings_section_formatting":  "Formatting",
    "settings_section_between":     "Remove Content Between",
    "settings_section_other":       "Other",
    "settings_chk_curly":           "Curly brackets  { }",
    "settings_chk_square":          "Square brackets  [ ]",
    "settings_chk_parens":          "Parentheses  ( )",
    "settings_chk_asterisk":        "Asterisks  * ... *",
    "settings_chk_hash":            "Hashtags  # ... #",
    "settings_chk_norm_case":       "Convert uppercase text to sentence case",
    "settings_chk_merge_dupe":      "Merge consecutive duplicate cues",
    "settings_lbl_language":        "Interface language:",
    "settings_lang_coming":         "Additional languages coming in v1.0.0",
    "settings_restart_required":    "Language changed. Restart SubForge to apply.",
    "settings_btn_restart":         "Restart Now",
    "addpattern_title":             "Always Mark as Ad — Add Pattern",
    "addpattern_grp_orig":          "Original subtitle block text",
    "addpattern_grp_regex":         "Regex pattern to add",
    "addpattern_hint":              "The pattern below was auto-generated from the block text. Edit it to be as specific or as broad as you need. All patterns are case-insensitive.",
    "addpattern_grp_profile":       "Save to profile",
    "addpattern_grp_level":         "Detection level",
    "addpattern_purge":             "PURGE — always remove (+ 3 pts)",
    "addpattern_warn":              "WARNING — flag for review (+ 1 pt)",
    "addpattern_btn_test":          "Test match against block text",
    "addpattern_match":             "✓ Pattern MATCHES the block text.",
    "addpattern_no_match":          "⚠ Pattern does NOT match the block text.\nIt will still be saved and applied to future files.",
    "addpattern_regex_error":       "✕ Regex error: {error}",
    "settings_btn_restart":         "Restart Now",
}

# ---------------------------------------------------------------------------
# Spanish
# ---------------------------------------------------------------------------

_ES: dict = {
    "app_title":                "SubForge",
    "app_toolbar_label":        "SubForge",
    "app_btn_settings":         "⚙ Ajustes",
    "app_btn_check_updates":    "Buscar actualizaciones",
    "app_btn_checking":         "Buscando...",
    "app_version":              "v0.8.0",
    "tab_single_file":          "Archivo único",
    "tab_batch":                "Lote",
    "tab_video_scan":           "Escanear vídeo",
    "tab_regex_editor":         "Editor de patrones",
    "sf_no_file_loaded":        "Ningún archivo cargado",
    "sf_loading":               "Cargando {name}…",
    "sf_lbl_file_queue":        "COLA DE ARCHIVOS",
    "sf_lbl_subtitle_blocks":   "BLOQUES DE SUBTÍTULOS",
    "sf_lbl_block_detail":      "DETALLE DEL BLOQUE",
    "sf_lbl_file_report":       "INFORME DEL ARCHIVO",
    "sf_chk_dry_run":           "Modo simulación",
    "sf_chk_remove_warnings":   "Eliminar advertencias",
    "sf_btn_open_folder":       "Abrir carpeta…",
    "sf_btn_mark_ad":           "Marcar como anuncio",
    "sf_btn_keep":              "Conservar bloque",
    "sf_btn_always_ad":         "Marcar siempre como anuncio...",
    "sf_btn_always_ad_tip":     "Añade un patrón regex para el texto de este bloque a un perfil,\npara que se marque automáticamente en todos los archivos futuros.",
    "sf_btn_prev":              "Archivo anterior",
    "sf_btn_next":              "Archivo siguiente",
    "sf_btn_clean_save":        "Limpiar y guardar",
    "sf_patterns_placeholder":  "Los patrones coincidentes aparecerán aquí…",
    "sf_drop_label":            "Suelta archivos de subtítulos aquí",
    "sf_drop_formats":          ".srt  .ass  .ssa  .vtt",
    "sf_browse":                "Examinar…",
    "sens_label":               "Sensibilidad:",
    "sens_more_aggressive":     "Más agresivo",
    "sens_more_conservative":   "Más conservador",
    "thresh_1":                 "Muy agresivo",
    "thresh_2":                 "Agresivo",
    "thresh_3":                 "Equilibrado (predeterminado)",
    "thresh_4":                 "Conservador",
    "thresh_5":                 "Muy conservador",
    "msg_ready":                "Listo — suelta archivos de subtítulos para comenzar",
    "msg_analysis_complete":    "Análisis completo — {ads} bloque(s) de anuncios encontrado(s), {warns} advertencia(s)",
    "msg_analysis_complete_opts": "Análisis completo — {ads} bloque(s) de anuncios, {warns} advertencia(s), {opts} opción(es)",
    "msg_error_loading":        "Error al cargar el archivo",
    "msg_error":                "Error: {msg}",
    "msg_no_blocks":            "Ningún bloque marcado para eliminar.",
    "msg_saved":                "Guardado: {name}",
    "msg_dry_run":              "Simulación completa — no se han escrito archivos.",
    "msg_engine_reloaded":      "Motor recargado — archivo reanálizado con nuevos patrones.",
    "dlg_confirm_title":        "Confirmar limpieza y guardado",
    "dlg_confirm_text":         "¿Eliminar {n} bloque(s) de {name}?",
    "dlg_write_error":          "Error de escritura",
    "msg_checking_updates":     "Buscando actualizaciones...",
    "msg_up_to_date":           "SubForge está actualizado.",
    "msg_update_failed":        "Error al buscar actualizaciones.",
    "dlg_update_available":     "Actualización disponible",
    "dlg_update_text":          "Hay una nueva versión de SubForge disponible.\n\nVersión actual:    {current}\nÚltima versión:    {latest}  ({name})\n\nVisita la página de versiones para descargar la actualización.",
    "dlg_up_to_date_title":     "Actualizado",
    "dlg_up_to_date_text":      "Estás usando la última versión de SubForge ({version}).",
    "dlg_update_failed_title":  "Error al buscar actualizaciones",
    "dlg_update_failed_text":   "No se pudieron buscar actualizaciones.\n\n{error}\n\nComprueba tu conexión a internet o visita:\n{url}",
    "batch_btn_select_folder":  "Seleccionar carpeta base…",
    "batch_no_folder":          "Ninguna carpeta seleccionada",
    "batch_btn_clear":          "Limpiar",
    "batch_btn_scan_all":       "Escanear todo",
    "batch_btn_clean_save_all": "Limpiar y guardar todo",
    "batch_btn_open_review":    "Abrir en Archivo único",
    "batch_btn_full_report":    "Ver informe completo",
    "batch_chk_warnings":       "Eliminar también advertencias (un nivel por debajo del umbral)",
    "batch_lbl_scanned":        "ARCHIVOS ESCANEADOS",
    "batch_lbl_report":         "INFORME DE LOTE",
    "batch_status_begin":       "Selecciona una carpeta de películas para comenzar.",
    "batch_status_scanning":    "Escaneando {current}/{total}: {name}",
    "batch_status_complete":    "Escaneo completo — {total} archivos · {with_ads} con anuncios ({blocks} bloques) · {warns} advertencias · umbral: rm>={thresh}",
    "batch_no_files":           "No se encontraron archivos de subtítulos en esa carpeta.",
    "batch_files_queued":       "{n} archivo(s) de subtítulos en cola.",
    "batch_saving":             "Guardando {i}/{total}: {name}",
    "batch_done_status":        "Listo — {saved} archivo(s) limpiado(s) con umbral rm>={thresh}.",
    "batch_tip_full_report":    "Restaurar el informe completo del lote.",
    "dlg_nothing_to_clean":     "Nada que limpiar",
    "dlg_nothing_to_clean_msg": "Ningún archivo tiene problemas en el umbral actual.",
    "dlg_confirm_batch":        "Confirmar limpieza por lotes",
    "dlg_confirm_batch_msg":    "¿Eliminar {blocks} bloque(s) de {files} archivo(s) y guardar?\n\nUmbral: regex_matches >= {thresh}\nEsta acción no se puede deshacer.",
    "dlg_saves_failed":         "Algunos guardados fallaron",
    "dlg_done":                 "Listo",
    "dlg_done_msg":             "{saved} archivo(s) limpiado(s) y guardado(s).",
    "video_btn_add_folder":     "Añadir carpeta…",
    "video_btn_clear":          "Limpiar",
    "video_btn_scan":           "Escanear vídeos",
    "video_btn_extract":        "Extraer y guardar .srt/.ass",
    "video_btn_remux":          "Limpiar y remezclar",
    "video_lbl_files":          "ARCHIVOS DE VÍDEO Y PISTAS",
    "video_lbl_detail":         "DETALLE DEL ESCANEO",
    "video_no_folder":          "Ninguna carpeta seleccionada",
    "video_chk_backup":         "Mantener copia de seguridad",
    "video_chk_warnings":       "Eliminar también advertencias",
    "video_drop_label":         "Suelta archivos de vídeo aquí  ·  .mkv  .mp4  .m4v",
    "video_status_complete":    "Escaneo completo — {total} vídeo(s) · {ads} bloque(s) de anuncios encontrado(s) en subtítulos incrustados",
    "video_lbl_selected":       "Marca las pistas detectadas para seleccionarlas para limpieza",
    "video_files_queued":       "{n} archivo(s) de vídeo en cola.",
    "video_status_begin":       "Suelta archivos de vídeo o añade una carpeta para comenzar.",
    "video_status_scanning":    "Escaneando {current}/{total}: {name}",
    "video_ffmpeg_notice":      "⚠  ffprobe y ffmpeg no encontrados en PATH. Instala FFmpeg (https://ffmpeg.org/download.html).",
    "video_mkv_notice":         "⚠  mkvmerge no encontrado — Limpiar y remezclar no está disponible para archivos MKV. Los archivos MP4 y M4V aún pueden remezclarse con FFmpeg. Instala MKVToolNix o configura la ruta en ⚙ Ajustes.",
    "video_remux_tip":          "Reconstruye el archivo de vídeo con las pistas de subtítulos limpias.",
    "video_extract_tip":        "Extrae y limpia las pistas de subtítulos como archivos independientes junto al vídeo.",
    "video_lbl_selected_n":     "{n} pista(s) seleccionada(s).",
    "video_starting":           "Iniciando…",
    "dlg_ffprobe_title":        "ffprobe no encontrado",
    "dlg_ffprobe_msg":          "Instala FFmpeg y asegúrate de que esté en tu PATH.",
    "dlg_extractions_failed":   "Algunas extracciones fallaron",
    "dlg_mkvmerge_missing":     "mkvmerge no encontrado",
    "dlg_mkvmerge_missing_msg": "Configura la ruta de mkvmerge en Ajustes en la barra de herramientas.",
    "regex_lbl_profiles":       "PERFILES",
    "regex_lbl_editor":         "EDITOR DE PATRONES",
    "regex_btn_new_profile":    "+ Nuevo perfil…",
    "regex_btn_reload":         "Recargar motor",
    "regex_btn_add":            "Añadir",
    "regex_btn_save":           "Guardar perfil",
    "regex_btn_discard":        "Descartar cambios",
    "regex_placeholder":        "Selecciona un perfil a la izquierda para editarlo…",
    "regex_desc":               "Edita perfiles regex directamente. Los cambios se guardan en disco y se aplican inmediatamente.",
    "regex_unsaved_title":      "Cambios sin guardar",
    "regex_unsaved_msg":        "Tienes cambios sin guardar. ¿Descartarlos?",
    "regex_valid":              "✓ Regex válido",
    "regex_invalid":            "✕ Inválido: {error}",
    "regex_dirty":              "● Cambios sin guardar",
    "regex_saved":              "✓ Guardado y motor recargado.",
    "regex_key_placeholder":    "clave (p. ej. mi_purga1)",
    "regex_val_placeholder":    r"valor regex (p. ej. \bMiMarca\b)",
    "dlg_invalid_regex":        "Regex inválido",
    "dlg_read_error":           "Error de lectura",
    "dlg_write_error_regex":    "Error de escritura",
    "dlg_invalid_config":       "Configuración inválida",
    "settings_title":               "Ajustes de SubForge",
    "settings_tab_general":         "General",
    "settings_tab_cleaning":        "Opciones de limpieza",
    "settings_tab_paths":           "Rutas",
    "settings_tab_about":           "Sobre",
    "settings_btn_save":            "Guardar",
    "settings_btn_cancel":          "Cancelar",
    "settings_grp_sensitivity":     "Sensibilidad predeterminada",
    "settings_sens_desc":           "Establece el nivel de sensibilidad inicial al iniciar SubForge. Se aplica a Archivo único, Lote y Escanear vídeo.",
    "settings_future_grp":          "Próximamente en v1.0.0",
    "settings_future_theme":        "Tema (oscuro / claro / alto contraste)",
    "settings_future_font":         "Tamaño de fuente (pequeño / mediano / grande)",
    "settings_future_lang":         "Idiomas adicionales",
    "settings_cleaning_desc":       "Estas opciones modifican el contenido de los subtítulos en el momento de la limpieza. Se aplican globalmente. Todas las opciones están desactivadas por defecto.",
    "settings_sdh_warn":            "Advertencia: Eliminar el contenido SDH reduce la accesibilidad para personas sordas o con dificultades auditivas.",
    "settings_grp_mkv":             "MKVToolNix",
    "settings_mkv_info":            "mkvmerge se usa para reconstruir archivos MKV con pistas de subtítulos limpias. Si no está en el PATH del sistema, especifica la ruta completa a mkvmerge.exe. No es necesario para archivos MP4 y M4V.",
    "settings_mkv_placeholder":     r"p. ej. C:\Archivos de programa\MKVToolNix\mkvmerge.exe",
    "settings_mkv_found":           "✓ Archivo encontrado.",
    "settings_mkv_not_found":       "✕ Archivo no encontrado en esa ruta.",
    "settings_mkv_on_path":         "✓ mkvmerge encontrado en PATH: {path}",
    "settings_mkv_missing":         "mkvmerge no encontrado. Instala desde https://mkvtoolnix.download/",
    "settings_browse":              "Examinar…",
    "settings_about_tagline":       "Elimina anuncios, marcas de agua y basura de distribuidores de archivos de subtítulos.",
    "settings_about_author":        "Creado por David R. Babcock",
    "settings_about_license":       "Publicado bajo la licencia MIT.",
    "settings_about_credit":        "Motor de detección basado originalmente en subcleaner de KBlixt (MIT).",
    "settings_btn_report_issue":    "Reportar un problema",
    "settings_chk_music":           "Eliminar indicaciones musicales",
    "settings_chk_music_tip":       "Elimina líneas compuestas íntegramente por símbolos musicales ♪ ♫.",
    "settings_chk_sdh":             "Eliminar anotaciones SDH",
    "settings_chk_sdh_tip":         "Elimina descripciones de sonido como [PUERTA SE CIERRA] y (RIENDO).",
    "settings_chk_speakers":        "Eliminar etiquetas de hablante",
    "settings_chk_speakers_tip":    "Elimina prefijos de hablante como JUAN: o - MARÍA: al inicio de las líneas.",
    "settings_chk_tags":            "Eliminar etiquetas de formato de texto",
    "settings_chk_tags_tip":        "Elimina etiquetas HTML. La cursiva y la negrita se pueden conservar.",
    "settings_chk_italic":          "Conservar cursiva  <i>",
    "settings_chk_bold":            "Conservar negrita  <b>",
    "settings_section_removal":     "Eliminación de contenido",
    "settings_section_formatting":  "Formato",
    "settings_section_between":     "Eliminar contenido entre",
    "settings_section_other":       "Otros",
    "settings_chk_curly":           "Llaves  { }",
    "settings_chk_square":          "Corchetes  [ ]",
    "settings_chk_parens":          "Paréntesis  ( )",
    "settings_chk_asterisk":        "Asteriscos  * ... *",
    "settings_chk_hash":            "Almohadillas  # ... #",
    "settings_chk_norm_case":       "Convertir texto en mayúsculas a formato oración",
    "settings_chk_merge_dupe":      "Combinar pistas duplicadas consecutivas",
    "settings_lbl_language":        "Idioma de la interfaz:",
    "settings_lang_coming":         "Idiomas adicionales disponibles en v1.0.0",
    "settings_restart_required":    "Idioma cambiado. Reinicia SubForge para aplicarlo.",
    "settings_btn_restart":         "Reiniciar ahora",
    "addpattern_title":             "Marcar siempre como anuncio — Añadir patrón",
    "addpattern_grp_orig":          "Texto original del bloque de subtítulo",
    "addpattern_grp_regex":         "Patrón regex a añadir",
    "addpattern_hint":              "El patrón siguiente se generó automáticamente a partir del texto del bloque. Edítalo para que sea tan específico o amplio como necesites. Todos los patrones no distinguen mayúsculas de minúsculas.",
    "addpattern_grp_profile":       "Guardar en perfil",
    "addpattern_grp_level":         "Nivel de detección",
    "addpattern_purge":             "PURGAR — eliminar siempre (+ 3 pts)",
    "addpattern_warn":              "ADVERTENCIA — marcar para revisión (+ 1 pt)",
    "addpattern_btn_test":          "Probar coincidencia con el texto del bloque",
    "addpattern_match":             "✓ El patrón COINCIDE con el texto del bloque.",
    "addpattern_no_match":          "⚠ El patrón NO coincide con el texto del bloque.\nIgualmente se guardará y se aplicará a archivos futuros.",
    "addpattern_regex_error":       "✕ Error de regex: {error}",
    "settings_btn_restart":         "Reiniciar ahora",
}

# ---------------------------------------------------------------------------
# Proxy — all modules import this once; set_language() updates it in place
# ---------------------------------------------------------------------------

LANGUAGES: dict = {"en": _EN, "es": _ES}
LANGUAGE_NAMES: dict = {"en": "English", "es": "Español"}


class _StringProxy:
    """Dict-like proxy that always reads from the active language dict.
    Falls back to English if a key is missing in the active language,
    and returns a visible placeholder if missing from English too."""
    def __init__(self):
        self._lang = "en"
        self._data = _EN

    def _set(self, lang_code: str):
        self._lang = lang_code
        self._data = LANGUAGES.get(lang_code, _EN)

    def __getitem__(self, key: str) -> str:
        # Try active language first, then English, then visible placeholder
        if key in self._data:
            return self._data[key]
        if key in _EN:
            return _EN[key]
        return f"[{key} — translation missing. Please report via ⚙ Settings > About > Report an Issue]"

    def get(self, key: str, default=None):
        if key in self._data:
            return self._data[key]
        if key in _EN:
            return _EN[key]
        return default

    def __contains__(self, key: str) -> bool:
        return key in self._data or key in _EN


STRINGS = _StringProxy()


def set_language(lang_code: str) -> None:
    """Switch active language. Takes effect immediately for all STRINGS lookups."""
    STRINGS._set(lang_code)


def get_language() -> str:
    return STRINGS._lang
